### ISSUE TITLE
I get an error when I test the Forward part.

### ISSUE THREAD

**Issue by jinwooklim** [HTLife/se3comp_pytorch#1]
I ran the `SE3CompTest.ipynb : Forward part` of your docker image environment and got the following error:

RuntimeError: inconsistent tensor size, expected r_ [2], t [2] and src [2 x 3 x 3] to have the same number of elements, but got 2, 2 and 18 elements respectively at /pytorch/torch/lib/TH/generic/THTensorMath.c:1036

How can I fix this error?

**Comment by HTLife** [comment]
I cannot reproduce this error on my computer.  What's your PyTorch and Python version?

I'm using PyTorch 0.4.0 and Python3.5.2

**Comment by jinwooklim** [comment]
The environment in which the error occurred was Pytorch 0.3.1 and Python 3.5.2

And I upgraded my version of pytorch to 0.4.0, then run it
The following error occurred again.

```
root@vinet /notebooks/vinet (master) $ python3 test_se3.py 
Traceback (most recent call last):
  File "test_se3.py", line 42, in <module>
    ans = model.forward(Tg, xi_vec)
          |             |   -> tensor([[[ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.]],

        [[ 0.],
         [ 0.]...
          |             -> tensor([[[ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.]],

        [[ 0.]...
          -> SE3Comp()
  File "/notebooks/vinet/SE3Comp.py", line 26, in forward
    R, V = self.so3_RV(torch.squeeze(omega))
           |           |             -> tensor([[[ 0.],
         [ 0.],
         [ 0.]],

        [[ 0.],
         [ 0.],
         [ 0.]]])
           |           -> <module 'torch' from '/usr/local/lib/python3.5/dist-packages/torch/__init__.py'>
           -> SE3Comp()
  File "/notebooks/vinet/SE3Comp.py", line 192, in so3_RV
    torch.mul(sin_theta_div_theta_tensor,omega_skew) +\
RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2
```


It is not run in the jupyter environment, it was run in .py file.
Is this a problem?

**Comment by HTLife** [comment]
I found the bug, which is caused by the broadcasting behavior of PyTorch.
[This line ](https://github.com/HTLife/se3comp_pytorch/blob/master/SE3Comp.py#L192) try to multiply a batch scalar (batch, 1) to a batch matrix (batch, 3, 3).  But PyTorch can't broadcast 1 to 3x3 automatically.  (Don't know why jupyter did not report this error.)

The solution is using **view** function to convert (batch, 3, 3) to (batch, 9).
The multiplication between (batch, 9) and (batch, 1) works fine.
And then we can convert the result back from (batch, 9) to (batch, 3, 3).

I just pushed a fix for this bug, check whether this fix also works on your machine or not.

**Comment by jinwooklim** [comment]
I confirmed your edits.

And, the code runs fine.

Thank you so much !!

**Comment by HTLife** [comment]
You are welcome!
By the way, are you trying to merge this implementation to VINet?

**Comment by jinwooklim** [comment]
Yes, I 'll merge it to VINet or to other VO models

**Comment by jinwooklim** [comment]
Unfortunately, if batch size is 1, the following error occurs:

```
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "main_fail.py", line 52, in forward
    R, V = self.so3_RV(torch.squeeze(omega))
  File "main_fail.py", line 145, in so3_RV
    omega_x = omega[:, 0]
IndexError: too many indices for tensor of dimension 1
```

**Comment by HTLife** [comment]
Thanks for reporting this issue.  A fixed version is already uploaded.

**Comment by jinwooklim** [comment]
Okay, I checked.
I'll tell you if there's an issue again.
